disabled_rules:
 - line_length
 - function_body_length
 - type_body_length
 - identifier_name
 - multiple_closures_with_trailing_closure
 - closure_body_length
 - file_length
 - weak_delegate
 - class_delegate_protocol
 - cyclomatic_complexity

opt_in_rules:
 - attributes
 - array_init
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - contains_over_first_not_nil
 - empty_count
 - empty_string
 - fallthrough
 - fatal_error_message
 - first_where
 - identical_operands
 - implicitly_unwrapped_optional
 - legacy_random
 - literal_expression_end_indentation
 - modifier_order
 - control_statement
 - trailing_newline
 - colon
 - comma
 - conditional_binding_cascade
 - explicit_init
 - redundant_nil_coalescing
 - syntactic_sugar

excluded:
- Pods
